### ISSUE TITLE
Cleanup of the code

### ISSUE THREAD

**Issue by ppapadeas** [jkramarz/K40-Whisperer#2]
Hello! Great work with the software!

Would you be OK with a couple of pull requests to do the following:

- Move images to a directory
- Clean up readme files
- Move the license file to LICENSE filename
- Package it for pypi
- Other minor improvements

**Comment by jkramarz** [comment]
Hi @ppapadeas, thank you for your proposition. Unfortunately, I'm not author nor developer of this software. Currently I'm only importing new releases periodically to track changes.

If you're interested in, please take a look at `master` branch, as I've started some code cleanup back in July. Unfortunately, it may be next to impossible to rebase it on v0.17.

On the other side, contacting original author (@scorchworks) may be beneficial for making this effort coordinated and sustainable.

**Comment by jkramarz** [comment]
@ppapadeas any thoughts? I'd be very happy to spend some time on Whisperer :grinning:

**Comment by tatarize** [comment]
@scorchworks doesn't seem too intent on making his own git for the files. There's some annoying issues with his code and I'm thinking a derivative hacked version might be needed to fix them and hopefully get him to put them into the main code. 

Like eyesore stuff, in just nano_library

* Hardcoded gui messages making translations require rewriting the driver.
* send_data() has two loops, if preprocess_crc is set to true: the first builds packets and second sends data, if false, the first sends the data and the second does nothing.
* send_data() when used to build packets builds a set of packets for every pass... identical packets.
* send_data() must build all the packets before trying to send the data. If you've ever run a raster engrave, do you wonder why it makes you wait a long time and then spends even longer doing the cutting? When it could simply start with the first data it has, then build the data as the whole thing is running?
* send_data() hammers the USB buffer with data until the buffer is no longer full, then sends the next data it calculated before this giant waiting game started. It literally just keeps sending the data inside a while (True) loop.
* waiting_for_laser_to_finish sits there in a similar while loop. Ignoring that it could just have a local state and lock that state refusing to issue laser commands until the task is complete. 
* wait_for_laser is called with a boolean sent to send_data, rather than just calling the function when you need it.
* line 164 is simply: "data[-4]" this is an integer, it does nothing.
* Send_data modifies the packet data for multiple passes doing egv stuff. Like not only is this stuff weirdly preprocessed rather than buffered like a stream, it also does some format specific editing of the stream in a weirdly coupled fashion.
* The send_data_with_error_checking sends the packet, then sends a hello packet and then reads the device response there.

...etc.

I mean the only one that seems to have a big impact on end users are the absurdist calculate every packet before you start sending any packets and be sure to calculate identical packets for you multiple passes things. Clearly you hit the button, and it should just start the laser. But, the weird coupling between the packetized sender to nano controller, and the egv-file-making. Seems to hamper some clear utility like writing a good command line interface etc. 

It doesn't need everything rewritten just the nano driver decoupled from the rest of the code and given a proper stream buffer. The egv interface does the interfacing everything so things like rapid_move aren't inexplicably in the nano_library. And a proper api built on top, so the stuff egv writes and sends to nano can just be controlled through an easy api that you don't need to see. Then the GUI is built on top of that project and properly doesn't directly control nano or even egv, but just issues a bunch of commands that are then encoded into egv and sent to nano. You could then have a generalized API to deal with laser cutters and then run other cutters rather then K40s with nano controllers.

Then pack the entire thing into pypi and just have K40 whisperer depend on the smaller package that does the mission critical stuff and most-helpfully also means other people could use this mission critical stuff without the giant gui interface.

**Comment by tatarize** [comment]
Rewrote the core elements and now better understand some of the design choices there. Also added in a CLI, https://github.com/tatarize/K40Nano some of the sending stuff is simply due to how the machine works. Namely you send it the entire file, it executes it, then says it's done. You could cut the file into different parts but then you'd have to check for the task complete flag before sending the next part of the file. etc. Some tiny wait amounts help but doesn't change the fundamentals of how it needs to run.

**Comment by tatarize** [comment]
This repository is merely version logging. #12
